/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resep;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASPIRE V5
 */
public class inputBahan extends javax.swing.JFrame {

    /**
     * Creates new form inputBahan
     */
    public inputBahan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bahan1textfield = new javax.swing.JTextField();
        bahan2textfield = new javax.swing.JTextField();
        bahan3textfield = new javax.swing.JTextField();
        tampilkaniButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampiltextArea = new javax.swing.JTextArea();
        cariResepButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MASUKKAN BAHAN YANG ADA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 0, 340, 60);
        getContentPane().add(bahan1textfield);
        bahan1textfield.setBounds(50, 60, 230, 40);
        getContentPane().add(bahan2textfield);
        bahan2textfield.setBounds(50, 110, 230, 40);

        bahan3textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bahan3textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(bahan3textfield);
        bahan3textfield.setBounds(50, 160, 230, 40);

        tampilkaniButton.setText("TAMPILKAN");
        tampilkaniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkaniButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tampilkaniButton);
        tampilkaniButton.setBounds(320, 100, 150, 40);

        tampiltextArea.setColumns(20);
        tampiltextArea.setRows(5);
        jScrollPane1.setViewportView(tampiltextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 370, 160);

        cariResepButton.setText("CARI RESEP");
        getContentPane().add(cariResepButton);
        cariResepButton.setBounds(390, 300, 100, 40);

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 243, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASPIRE V5\\Documents\\PROYEK OOP\\Light-Wood-Background-Wallpaper.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 390);

        setSize(new java.awt.Dimension(522, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bahan3textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bahan3textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bahan3textfieldActionPerformed

    private void tampilkaniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkaniButtonActionPerformed
String bahan1=bahan1textfield.getText();
String bahan2=bahan2textfield.getText();
String bahan3=bahan3textfield.getText();
String resep;
String kode;

try{
        Class.forName("com.mysql.jdbc.Driver");
             Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/resep_makanan1","resep","0");
             Statement statement = connection.createStatement();
             String sql="select nama_resep from resep where bahan LIKE '%"+bahan1+"%' AND bahan LIKE '%"+bahan2+"%'"
                     + "AND bahan LIKE '%"+bahan3+"%'";
             ResultSet rs = statement.executeQuery(sql);
             while(rs.next()){
                 resep=(rs.getString("nama_resep"));
                                
                 tampiltextArea.append(resep+" ,\n");
                               
             }
             statement.close();
    }catch (Exception e){
            JOptionPane.showMessageDialog(null, "ada kesalahan \n"+e);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tampilkaniButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
bahan1textfield.setText("");
bahan2textfield.setText("");
bahan3textfield.setText("");
tampiltextArea.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputBahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bahan1textfield;
    private javax.swing.JTextField bahan2textfield;
    private javax.swing.JTextField bahan3textfield;
    private javax.swing.JButton cariResepButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tampilkaniButton;
    private javax.swing.JTextArea tampiltextArea;
    // End of variables declaration//GEN-END:variables
}
